apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- .././base
- ./resources/RoleBinding.yaml
- ./resources/Route.yaml
- ./resources/ConfigMap/ldap-config.yaml

patches:

- path: resources/ConfigMap/grafana-ini.yaml
- path: resources/Deployment/grafana.yaml

- target:
    version: v1
    kind: Service
    name: kube-prom-stack-prometheus-node-exporter
  patch: |-
    - op: replace
      path: /spec/ports/0/port
      value: 9123
    - op: replace
      path: /spec/ports/0/targetPort
      value: 9123

- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: kube-prom-stack-prometheus-node-exporter
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args/3
      value: --web.listen-address=[$(HOST_IP)]:9123
    - op: replace
      path: /spec/template/spec/containers/0/ports/0/containerPort
      value: 9123
    - op: replace
      path: /spec/template/spec/containers/0/livenessProbe/httpGet/port
      value: 9123
    - op: replace
      path: /spec/template/spec/containers/0/readinessProbe/httpGet/port
      value: 9123

- target:
    group: apps
    version: v1
    kind: Deployment
    name: kube-prom-stack-kube-prome-operator
  patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/args/8
      value: --web.enable-tls=true
    - op: remove
      path: /spec/template/spec/containers/0/args/8
      value: --web.cert-file=/cert/cert
    - op: remove
      path: /spec/template/spec/containers/0/args/8
      value: ---web.key-file=/cert/key
    - op: remove
      path: /spec/template/spec/containers/0/args/8
      value: --web.listen-address=:10250
    - op: remove
      path: /spec/template/spec/containers/0/args/8
      value: ---web.tls-min-version=VersionTLS13
    - op: remove
      path: /spec/template/spec/containers/0/volumeMounts
    - op: remove
      path: /spec/template/spec/volumes
    - op: replace
      path: /spec/replicas
      value: 1
